import { Quote } from '../types';

export const mockQuotes: Quote[] = [
  { id: 'q1', requestId: 'sr1', workerId: 'w1', workerName: 'Juan Pérez Mendoza', workerRating: 4.8, amount: 850, description: 'Reparación de fuga en tubería del lavabo. Incluye revisión y mano de obra.', estimatedDuration: '2-3 horas', includesMaterials: true, materialsCost: 200, createdAt: '2024-07-12T14:00:00Z', status: 'accepted' },
  { id: 'q2', requestId: 'sr1', workerId: 'w12', workerName: 'Luis Enrique Mora', workerRating: 4.5, amount: 1200, description: 'Diagnóstico y reparación de fuga. Materiales no incluidos.', estimatedDuration: '3-4 horas', includesMaterials: false, createdAt: '2024-07-12T16:00:00Z', status: 'rejected' },
  { id: 'q3', requestId: 'sr2', workerId: 'w2', workerName: 'Ricardo Gómez Salinas', workerRating: 4.9, amount: 750, description: 'Revisión del circuito eléctrico de cocina y comedor. Reparación de la falla.', estimatedDuration: '1-2 horas', includesMaterials: true, materialsCost: 150, createdAt: '2024-07-14T11:00:00Z', status: 'pending' },
  { id: 'q4', requestId: 'sr4', workerId: 'w4', workerName: 'Isabel Navarro Cruz', workerRating: 4.9, amount: 1800, description: 'Limpieza profunda completa. Incluye productos y equipo.', estimatedDuration: '5-6 horas', includesMaterials: true, materialsCost: 300, createdAt: '2024-06-20T14:00:00Z', status: 'accepted' },
  { id: 'q5', requestId: 'sr5', workerId: 'w5', workerName: 'Alejandro Moreno Ríos', workerRating: 4.6, amount: 600, description: 'Apertura de puerta sin daño. Servicio de emergencia.', estimatedDuration: '30-60 min', includesMaterials: true, materialsCost: 0, createdAt: '2024-07-10T20:15:00Z', status: 'accepted' },
  { id: 'q6', requestId: 'sr7', workerId: 'w2', workerName: 'Ricardo Gómez Salinas', workerRating: 4.9, amount: 2400, description: 'Instalación de 8 lámparas LED. Incluye materiales básicos.', estimatedDuration: '4-5 horas', includesMaterials: true, materialsCost: 800, createdAt: '2024-07-14T10:00:00Z', status: 'pending' },
  { id: 'q7', requestId: 'sr7', workerId: 'w10', workerName: 'Óscar Vázquez Rojas', workerRating: 4.6, amount: 2000, description: 'Cambio de 8 lámparas a LED. Materiales por cuenta del cliente.', estimatedDuration: '3-4 horas', includesMaterials: false, createdAt: '2024-07-14T12:00:00Z', status: 'pending' },
  { id: 'q8', requestId: 'sr8', workerId: 'w7', workerName: 'Raúl Delgado Fuentes', workerRating: 4.7, amount: 1200, description: 'Poda de 3 árboles y arbustos. Incluye recolección de basura verde.', estimatedDuration: '4-5 horas', includesMaterials: true, materialsCost: 0, createdAt: '2024-07-12T09:00:00Z', status: 'accepted' },
  { id: 'q9', requestId: 'sr11', workerId: 'w6', workerName: 'Martín Aguilar Peña', workerRating: 4.5, amount: 4500, description: 'Mudanza completa con empaque. Camión de 3.5 toneladas. 2 ayudantes.', estimatedDuration: '6-8 horas', includesMaterials: true, materialsCost: 500, createdAt: '2024-07-11T09:00:00Z', status: 'accepted' },
  { id: 'q10', requestId: 'sr10', workerId: 'w11', workerName: 'Patricia Solís Campos', workerRating: 4.9, amount: 3500, description: 'Limpieza post-construcción completa. Equipo profesional incluido.', estimatedDuration: '8-10 horas', includesMaterials: true, materialsCost: 500, createdAt: '2024-07-12T16:00:00Z', status: 'accepted' },
  { id: 'q11', requestId: 'sr15', workerId: 'w14', workerName: 'Andrés Figueroa Nava', workerRating: 4.7, amount: 800, description: 'Instalación de 4 repisas flotantes. Perforación y fijación incluidas.', estimatedDuration: '2-3 horas', includesMaterials: true, materialsCost: 200, createdAt: '2024-07-14T08:00:00Z', status: 'pending' },
  { id: 'q12', requestId: 'sr20', workerId: 'w14', workerName: 'Andrés Figueroa Nava', workerRating: 4.7, amount: 8500, description: 'Muro de tablaroca con puerta. Incluye estructura metálica y acabados.', estimatedDuration: '2-3 días', includesMaterials: true, materialsCost: 3500, createdAt: '2024-07-13T14:00:00Z', status: 'pending' },
  { id: 'q13', requestId: 'sr13', workerId: 'w2', workerName: 'Ricardo Gómez Salinas', workerRating: 4.9, amount: 3200, description: 'Cambio completo de centro de carga con 12 interruptores termomagnéticos.', estimatedDuration: '4-6 horas', includesMaterials: true, materialsCost: 1800, createdAt: '2024-06-25T14:00:00Z', status: 'accepted' },
];
