import { ServiceRequest } from '../types';

export const mockRequests: ServiceRequest[] = [
  {
    id: 'sr1', userId: 'u1', categoryId: 'plomeria', subcategoryId: 'p1', title: 'Fuga de agua en el baño',
    description: 'Tengo una fuga de agua debajo del lavabo del baño principal. Lleva dos días goteando y ya se formó un charco.',
    photos: ['https://placehold.co/400x300/DBEAFE/2563EB?text=Fuga'], urgency: 'high',
    status: 'in_progress', address: { street: 'Av. Reforma 222', colony: 'Juárez', city: 'Ciudad de México', state: 'CDMX', zipCode: '06600' },
    preferredDate: '2024-07-15', preferredTime: '10:00', createdAt: '2024-07-12T10:30:00Z', updatedAt: '2024-07-14T09:00:00Z',
    assignedWorkerId: 'w1', acceptedQuoteId: 'q1',
    timeline: [
      { id: 't1', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-12T10:30:00Z', actor: 'María García López' },
      { id: 't2', type: 'quoted', description: 'Cotización recibida de Juan Pérez', timestamp: '2024-07-12T14:00:00Z', actor: 'Juan Pérez Mendoza' },
      { id: 't3', type: 'accepted', description: 'Cotización aceptada', timestamp: '2024-07-13T08:00:00Z', actor: 'María García López' },
      { id: 't4', type: 'in_progress', description: 'Trabajo iniciado', timestamp: '2024-07-14T09:00:00Z', actor: 'Juan Pérez Mendoza' },
    ],
  },
  {
    id: 'sr2', userId: 'u2', categoryId: 'electricidad', subcategoryId: 'e1', title: 'Apagón en la cocina',
    description: 'Se fue la luz en la cocina y el comedor. El resto de la casa funciona normal. Revisé los interruptores pero no encontré nada.',
    photos: [], urgency: 'medium', status: 'quoted',
    address: { street: 'Calle Monterrey 45', colony: 'Roma Sur', city: 'Ciudad de México', state: 'CDMX', zipCode: '06700' },
    createdAt: '2024-07-13T15:00:00Z', updatedAt: '2024-07-14T11:00:00Z',
    timeline: [
      { id: 't5', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-13T15:00:00Z', actor: 'Carlos Hernández Ruiz' },
      { id: 't6', type: 'quoted', description: 'Cotización recibida de Ricardo Gómez', timestamp: '2024-07-14T11:00:00Z', actor: 'Ricardo Gómez Salinas' },
    ],
  },
  {
    id: 'sr3', userId: 'u3', categoryId: 'pintura', subcategoryId: 'pi1', title: 'Pintar sala y recámara',
    description: 'Necesito pintar la sala y la recámara principal. Aproximadamente 60m² en total. Quiero colores claros.',
    photos: [], urgency: 'low', status: 'pending',
    address: { street: 'Av. Vallarta 1200', colony: 'Americana', city: 'Guadalajara', state: 'Jalisco', zipCode: '44160' },
    createdAt: '2024-07-14T09:00:00Z', updatedAt: '2024-07-14T09:00:00Z',
    timeline: [
      { id: 't7', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-14T09:00:00Z', actor: 'Ana Martínez Flores' },
    ],
  },
  {
    id: 'sr4', userId: 'u1', categoryId: 'limpieza', subcategoryId: 'l1', title: 'Limpieza profunda departamento',
    description: 'Limpieza profunda de departamento de 2 recámaras. Incluye cocina, baños, ventanas y pisos.',
    photos: [], urgency: 'medium', status: 'completed',
    address: { street: 'Av. Reforma 222', colony: 'Juárez', city: 'Ciudad de México', state: 'CDMX', zipCode: '06600' },
    createdAt: '2024-06-20T10:00:00Z', updatedAt: '2024-06-22T16:00:00Z',
    assignedWorkerId: 'w4', acceptedQuoteId: 'q4', completedAt: '2024-06-22T16:00:00Z',
    timeline: [
      { id: 't8', type: 'created', description: 'Solicitud creada', timestamp: '2024-06-20T10:00:00Z', actor: 'María García López' },
      { id: 't9', type: 'quoted', description: 'Cotización recibida', timestamp: '2024-06-20T14:00:00Z', actor: 'Isabel Navarro Cruz' },
      { id: 't10', type: 'accepted', description: 'Cotización aceptada', timestamp: '2024-06-21T08:00:00Z', actor: 'María García López' },
      { id: 't11', type: 'in_progress', description: 'Trabajo iniciado', timestamp: '2024-06-22T09:00:00Z', actor: 'Isabel Navarro Cruz' },
      { id: 't12', type: 'completed', description: 'Trabajo completado', timestamp: '2024-06-22T16:00:00Z', actor: 'Isabel Navarro Cruz' },
    ],
  },
  {
    id: 'sr5', userId: 'u4', categoryId: 'cerrajeria', subcategoryId: 'ce1', title: 'Me quedé fuera de casa',
    description: 'Perdí mis llaves y no puedo entrar a mi departamento. Necesito un cerrajero urgente.',
    photos: [], urgency: 'emergency', status: 'completed',
    address: { street: 'Calzada del Valle 100', colony: 'Del Valle', city: 'Monterrey', state: 'Nuevo León', zipCode: '66220' },
    createdAt: '2024-07-10T20:00:00Z', updatedAt: '2024-07-10T22:00:00Z',
    assignedWorkerId: 'w5', acceptedQuoteId: 'q5', completedAt: '2024-07-10T22:00:00Z',
    timeline: [
      { id: 't13', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-10T20:00:00Z', actor: 'Roberto Sánchez Díaz' },
      { id: 't14', type: 'quoted', description: 'Cotización inmediata', timestamp: '2024-07-10T20:15:00Z', actor: 'Alejandro Moreno Ríos' },
      { id: 't15', type: 'accepted', description: 'Cotización aceptada', timestamp: '2024-07-10T20:20:00Z', actor: 'Roberto Sánchez Díaz' },
      { id: 't16', type: 'completed', description: 'Puerta abierta exitosamente', timestamp: '2024-07-10T22:00:00Z', actor: 'Alejandro Moreno Ríos' },
    ],
  },
  {
    id: 'sr6', userId: 'u5', categoryId: 'plomeria', subcategoryId: 'p2', title: 'Drenaje tapado en cocina',
    description: 'El drenaje de la cocina está completamente tapado. El agua no baja desde hace dos días.',
    photos: ['https://placehold.co/400x300/DBEAFE/2563EB?text=Drenaje'], urgency: 'high', status: 'pending',
    address: { street: 'Av. Insurgentes Sur 500', colony: 'Del Valle', city: 'Ciudad de México', state: 'CDMX', zipCode: '03100' },
    createdAt: '2024-07-14T11:00:00Z', updatedAt: '2024-07-14T11:00:00Z',
    timeline: [
      { id: 't17', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-14T11:00:00Z', actor: 'Laura Rodríguez Morales' },
    ],
  },
  {
    id: 'sr7', userId: 'u6', categoryId: 'electricidad', subcategoryId: 'e4', title: 'Instalar lámparas LED',
    description: 'Quiero cambiar todas las lámparas de mi casa por LED. Son 8 lámparas en total.',
    photos: [], urgency: 'low', status: 'quoted',
    address: { street: 'Calle Durango 200', colony: 'Roma Norte', city: 'Ciudad de México', state: 'CDMX', zipCode: '06700' },
    createdAt: '2024-07-13T08:00:00Z', updatedAt: '2024-07-14T10:00:00Z',
    timeline: [
      { id: 't18', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-13T08:00:00Z', actor: 'Pedro López Castro' },
      { id: 't19', type: 'quoted', description: 'Cotización recibida', timestamp: '2024-07-14T10:00:00Z', actor: 'Ricardo Gómez Salinas' },
    ],
  },
  {
    id: 'sr8', userId: 'u7', categoryId: 'jardineria', subcategoryId: 'j1', title: 'Poda de árboles y arbustos',
    description: 'Necesito podar 3 árboles y varios arbustos en mi jardín. El jardín es de aproximadamente 100m².',
    photos: ['https://placehold.co/400x300/D1FAE5/059669?text=Jardin'], urgency: 'low', status: 'accepted',
    address: { street: 'Blvd. Atlixcáyotl 1001', colony: 'Reserva Territorial', city: 'Puebla', state: 'Puebla', zipCode: '72810' },
    createdAt: '2024-07-11T14:00:00Z', updatedAt: '2024-07-13T10:00:00Z',
    assignedWorkerId: 'w7',
    timeline: [
      { id: 't20', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-11T14:00:00Z', actor: 'Fernanda Torres Vega' },
      { id: 't21', type: 'quoted', description: 'Cotización recibida', timestamp: '2024-07-12T09:00:00Z', actor: 'Raúl Delgado Fuentes' },
      { id: 't22', type: 'accepted', description: 'Cotización aceptada', timestamp: '2024-07-13T10:00:00Z', actor: 'Fernanda Torres Vega' },
    ],
  },
  {
    id: 'sr9', userId: 'u8', categoryId: 'general', subcategoryId: 'g1', title: 'Reparar puerta de madera',
    description: 'La puerta de la recámara principal no cierra bien. Necesita ajuste o cambio de bisagras.',
    photos: [], urgency: 'medium', status: 'pending',
    address: { street: 'Av. Revolución 300', colony: 'Tacubaya', city: 'Ciudad de México', state: 'CDMX', zipCode: '11870' },
    createdAt: '2024-07-14T07:00:00Z', updatedAt: '2024-07-14T07:00:00Z',
    timeline: [
      { id: 't23', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-14T07:00:00Z', actor: 'Diego Ramírez Ortega' },
    ],
  },
  {
    id: 'sr10', userId: 'u9', categoryId: 'limpieza', subcategoryId: 'l3', title: 'Limpieza post-remodelación',
    description: 'Acabo de remodelar la cocina y necesito una limpieza profunda de toda la casa. Hay polvo y escombro.',
    photos: ['https://placehold.co/400x300/EDE9FE/8B5CF6?text=Post+Obra'], urgency: 'high', status: 'in_progress',
    address: { street: 'Av. Universidad 700', colony: 'Narvarte', city: 'Ciudad de México', state: 'CDMX', zipCode: '03020' },
    createdAt: '2024-07-12T11:00:00Z', updatedAt: '2024-07-14T08:00:00Z',
    assignedWorkerId: 'w11', acceptedQuoteId: 'q10',
    timeline: [
      { id: 't24', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-12T11:00:00Z', actor: 'Sofía Jiménez Reyes' },
      { id: 't25', type: 'quoted', description: 'Cotización recibida', timestamp: '2024-07-12T16:00:00Z', actor: 'Patricia Solís Campos' },
      { id: 't26', type: 'accepted', description: 'Cotización aceptada', timestamp: '2024-07-13T09:00:00Z', actor: 'Sofía Jiménez Reyes' },
      { id: 't27', type: 'in_progress', description: 'Trabajo iniciado', timestamp: '2024-07-14T08:00:00Z', actor: 'Patricia Solís Campos' },
    ],
  },
  {
    id: 'sr11', userId: 'u2', categoryId: 'mudanzas', subcategoryId: 'm1', title: 'Mudanza de depa a casa',
    description: 'Me mudo de un departamento de 2 recámaras a una casa. Necesito empaque, transporte y desempaque.',
    photos: [], urgency: 'medium', status: 'accepted',
    address: { street: 'Calle Monterrey 45', colony: 'Roma Sur', city: 'Ciudad de México', state: 'CDMX', zipCode: '06700' },
    createdAt: '2024-07-10T10:00:00Z', updatedAt: '2024-07-12T15:00:00Z',
    assignedWorkerId: 'w6',
    timeline: [
      { id: 't28', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-10T10:00:00Z', actor: 'Carlos Hernández Ruiz' },
      { id: 't29', type: 'quoted', description: 'Cotización recibida', timestamp: '2024-07-11T09:00:00Z', actor: 'Martín Aguilar Peña' },
      { id: 't30', type: 'accepted', description: 'Cotización aceptada', timestamp: '2024-07-12T15:00:00Z', actor: 'Carlos Hernández Ruiz' },
    ],
  },
  {
    id: 'sr12', userId: 'u10', categoryId: 'pintura', subcategoryId: 'pi3', title: 'Impermeabilizar azotea',
    description: 'Necesito impermeabilizar la azotea de mi casa. Son aproximadamente 80m². Ya tiene goteras.',
    photos: [], urgency: 'high', status: 'pending',
    address: { street: 'Calle Liverpool 50', colony: 'Juárez', city: 'Ciudad de México', state: 'CDMX', zipCode: '06600' },
    createdAt: '2024-07-14T13:00:00Z', updatedAt: '2024-07-14T13:00:00Z',
    timeline: [
      { id: 't31', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-14T13:00:00Z', actor: 'Miguel Ángel Vargas' },
    ],
  },
  {
    id: 'sr13', userId: 'u5', categoryId: 'electricidad', subcategoryId: 'e3', title: 'Cambiar centro de carga',
    description: 'Mi centro de carga es muy viejo y se sobrecalienta. Necesito cambio completo con interruptores nuevos.',
    photos: ['https://placehold.co/400x300/FEF3C7/F59E0B?text=Centro+Carga'], urgency: 'high', status: 'completed',
    address: { street: 'Av. Insurgentes Sur 500', colony: 'Del Valle', city: 'Ciudad de México', state: 'CDMX', zipCode: '03100' },
    createdAt: '2024-06-25T08:00:00Z', updatedAt: '2024-06-28T17:00:00Z',
    assignedWorkerId: 'w2', acceptedQuoteId: 'q13', completedAt: '2024-06-28T17:00:00Z',
    timeline: [
      { id: 't32', type: 'created', description: 'Solicitud creada', timestamp: '2024-06-25T08:00:00Z', actor: 'Laura Rodríguez Morales' },
      { id: 't33', type: 'completed', description: 'Centro de carga instalado', timestamp: '2024-06-28T17:00:00Z', actor: 'Ricardo Gómez Salinas' },
    ],
  },
  {
    id: 'sr14', userId: 'u3', categoryId: 'limpieza', subcategoryId: 'l2', title: 'Limpieza semanal regular',
    description: 'Busco servicio de limpieza semanal para casa de 3 recámaras. Todos los miércoles.',
    photos: [], urgency: 'low', status: 'completed',
    address: { street: 'Av. Vallarta 1200', colony: 'Americana', city: 'Guadalajara', state: 'Jalisco', zipCode: '44160' },
    createdAt: '2024-06-01T10:00:00Z', updatedAt: '2024-06-05T14:00:00Z',
    assignedWorkerId: 'w4', completedAt: '2024-06-05T14:00:00Z',
    timeline: [
      { id: 't34', type: 'created', description: 'Solicitud creada', timestamp: '2024-06-01T10:00:00Z', actor: 'Ana Martínez Flores' },
      { id: 't35', type: 'completed', description: 'Servicio completado', timestamp: '2024-06-05T14:00:00Z', actor: 'Isabel Navarro Cruz' },
    ],
  },
  {
    id: 'sr15', userId: 'u6', categoryId: 'general', subcategoryId: 'g4', title: 'Instalar repisas flotantes',
    description: 'Quiero instalar 4 repisas flotantes en la sala. Ya tengo las repisas, solo necesito instalación.',
    photos: [], urgency: 'low', status: 'quoted',
    address: { street: 'Calle Durango 200', colony: 'Roma Norte', city: 'Ciudad de México', state: 'CDMX', zipCode: '06700' },
    createdAt: '2024-07-13T12:00:00Z', updatedAt: '2024-07-14T08:00:00Z',
    timeline: [
      { id: 't36', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-13T12:00:00Z', actor: 'Pedro López Castro' },
      { id: 't37', type: 'quoted', description: 'Cotización recibida', timestamp: '2024-07-14T08:00:00Z', actor: 'Andrés Figueroa Nava' },
    ],
  },
  {
    id: 'sr16', userId: 'u8', categoryId: 'plomeria', subcategoryId: 'p4', title: 'Instalar calentador solar',
    description: 'Quiero cambiar mi boiler de gas por un calentador solar. Casa de 2 pisos, 2 baños.',
    photos: [], urgency: 'low', status: 'pending',
    address: { street: 'Av. Revolución 300', colony: 'Tacubaya', city: 'Ciudad de México', state: 'CDMX', zipCode: '11870' },
    createdAt: '2024-07-14T15:00:00Z', updatedAt: '2024-07-14T15:00:00Z',
    timeline: [
      { id: 't38', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-14T15:00:00Z', actor: 'Diego Ramírez Ortega' },
    ],
  },
  {
    id: 'sr17', userId: 'u4', categoryId: 'cerrajeria', subcategoryId: 'ce2', title: 'Cambiar chapas de toda la casa',
    description: 'Quiero cambiar todas las chapas de la casa por seguridad. Son 3 puertas exteriores.',
    photos: [], urgency: 'medium', status: 'cancelled',
    address: { street: 'Calzada del Valle 100', colony: 'Del Valle', city: 'Monterrey', state: 'Nuevo León', zipCode: '66220' },
    createdAt: '2024-07-05T10:00:00Z', updatedAt: '2024-07-08T12:00:00Z',
    timeline: [
      { id: 't39', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-05T10:00:00Z', actor: 'Roberto Sánchez Díaz' },
      { id: 't40', type: 'cancelled', description: 'Solicitud cancelada por el usuario', timestamp: '2024-07-08T12:00:00Z', actor: 'Roberto Sánchez Díaz' },
    ],
  },
  {
    id: 'sr18', userId: 'u1', categoryId: 'jardineria', subcategoryId: 'j2', title: 'Diseñar jardín en terraza',
    description: 'Tengo una terraza de 20m² y quiero convertirla en un jardín con plantas y sistema de riego.',
    photos: [], urgency: 'low', status: 'disputed',
    address: { street: 'Av. Reforma 222', colony: 'Juárez', city: 'Ciudad de México', state: 'CDMX', zipCode: '06600' },
    createdAt: '2024-06-15T10:00:00Z', updatedAt: '2024-07-01T10:00:00Z',
    assignedWorkerId: 'w7', completedAt: '2024-06-28T15:00:00Z',
    timeline: [
      { id: 't41', type: 'created', description: 'Solicitud creada', timestamp: '2024-06-15T10:00:00Z', actor: 'María García López' },
      { id: 't42', type: 'disputed', description: 'Disputa abierta por el usuario', timestamp: '2024-07-01T10:00:00Z', actor: 'María García López' },
    ],
  },
  {
    id: 'sr19', userId: 'u9', categoryId: 'pintura', subcategoryId: 'pi2', title: 'Pintar fachada de casa',
    description: 'Necesito pintar la fachada de mi casa. Tiene detalles en cantera que necesitan limpieza previa.',
    photos: ['https://placehold.co/400x300/D1FAE5/10B981?text=Fachada'], urgency: 'medium', status: 'pending',
    address: { street: 'Av. Universidad 700', colony: 'Narvarte', city: 'Ciudad de México', state: 'CDMX', zipCode: '03020' },
    createdAt: '2024-07-14T16:00:00Z', updatedAt: '2024-07-14T16:00:00Z',
    timeline: [
      { id: 't43', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-14T16:00:00Z', actor: 'Sofía Jiménez Reyes' },
    ],
  },
  {
    id: 'sr20', userId: 'u7', categoryId: 'general', subcategoryId: 'g3', title: 'Instalar muro de tablaroca',
    description: 'Necesito dividir una recámara grande en dos. Muro de tablaroca con puerta.',
    photos: [], urgency: 'medium', status: 'quoted',
    address: { street: 'Blvd. Atlixcáyotl 1001', colony: 'Reserva Territorial', city: 'Puebla', state: 'Puebla', zipCode: '72810' },
    createdAt: '2024-07-12T09:00:00Z', updatedAt: '2024-07-13T14:00:00Z',
    timeline: [
      { id: 't44', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-12T09:00:00Z', actor: 'Fernanda Torres Vega' },
      { id: 't45', type: 'quoted', description: 'Cotización recibida', timestamp: '2024-07-13T14:00:00Z', actor: 'Andrés Figueroa Nava' },
    ],
  },
  // Modelo
  {
    id: 'sr21', userId: 'u5', categoryId: 'modelo', subcategoryId: 'mo1', title: 'Sesión de fotos para mi marca de ropa',
    description: 'Necesito una modelo para sesión fotográfica de mi nueva colección de ropa. Son 20 outfits, sesión en estudio profesional en Polanco.',
    photos: [], urgency: 'medium', status: 'quoted',
    address: { street: 'Av. Insurgentes Sur 500', colony: 'Del Valle', city: 'Ciudad de México', state: 'CDMX', zipCode: '03100' },
    createdAt: '2024-07-13T10:00:00Z', updatedAt: '2024-07-14T09:00:00Z',
    timeline: [
      { id: 't46', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-13T10:00:00Z', actor: 'Laura Rodríguez Morales' },
      { id: 't47', type: 'quoted', description: 'Cotización recibida de Valentina Ríos', timestamp: '2024-07-14T09:00:00Z', actor: 'Valentina Ríos Estrada' },
    ],
  },
  {
    id: 'sr22', userId: 'u2', categoryId: 'modelo', subcategoryId: 'mo4', title: 'Modelo para comercial de TV',
    description: 'Grabación de comercial para marca de bebidas. Se requiere modelo con experiencia frente a cámara. Filmación de 1 día.',
    photos: [], urgency: 'high', status: 'in_progress',
    address: { street: 'Calle Monterrey 45', colony: 'Roma Sur', city: 'Ciudad de México', state: 'CDMX', zipCode: '06700' },
    createdAt: '2024-07-11T08:00:00Z', updatedAt: '2024-07-14T07:00:00Z',
    assignedWorkerId: 'w17', acceptedQuoteId: 'q22',
    timeline: [
      { id: 't48', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-11T08:00:00Z', actor: 'Carlos Hernández Ruiz' },
      { id: 't49', type: 'quoted', description: 'Cotización recibida', timestamp: '2024-07-11T16:00:00Z', actor: 'Daniela Campos Herrera' },
      { id: 't50', type: 'accepted', description: 'Cotización aceptada', timestamp: '2024-07-12T09:00:00Z', actor: 'Carlos Hernández Ruiz' },
      { id: 't51', type: 'in_progress', description: 'Grabación iniciada', timestamp: '2024-07-14T07:00:00Z', actor: 'Daniela Campos Herrera' },
    ],
  },
  // Influencer
  {
    id: 'sr23', userId: 'u10', categoryId: 'influencer', subcategoryId: 'in1', title: 'Post patrocinado para restaurante',
    description: 'Busco influencer de comida/lifestyle para publicar reseña de mi restaurante en Instagram. Mínimo 50K seguidores.',
    photos: ['https://placehold.co/400x300/FFF7ED/F97316?text=Restaurante'], urgency: 'medium', status: 'pending',
    address: { street: 'Calle Liverpool 50', colony: 'Juárez', city: 'Ciudad de México', state: 'CDMX', zipCode: '06600' },
    createdAt: '2024-07-14T12:00:00Z', updatedAt: '2024-07-14T12:00:00Z',
    timeline: [
      { id: 't52', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-14T12:00:00Z', actor: 'Miguel Ángel Vargas' },
    ],
  },
  {
    id: 'sr24', userId: 'u3', categoryId: 'influencer', subcategoryId: 'in5', title: 'Campaña de lanzamiento de producto',
    description: 'Lanzamos una nueva línea de skincare y necesitamos una campaña completa: 3 posts, 5 stories y 2 reels durante un mes.',
    photos: [], urgency: 'low', status: 'accepted',
    address: { street: 'Av. Vallarta 1200', colony: 'Americana', city: 'Guadalajara', state: 'Jalisco', zipCode: '44160' },
    createdAt: '2024-07-10T09:00:00Z', updatedAt: '2024-07-13T11:00:00Z',
    assignedWorkerId: 'w19',
    timeline: [
      { id: 't53', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-10T09:00:00Z', actor: 'Ana Martínez Flores' },
      { id: 't54', type: 'quoted', description: 'Cotización recibida de Mariana López', timestamp: '2024-07-11T10:00:00Z', actor: 'Mariana López Durán' },
      { id: 't55', type: 'accepted', description: 'Cotización aceptada', timestamp: '2024-07-13T11:00:00Z', actor: 'Ana Martínez Flores' },
    ],
  },
  // Edecán
  {
    id: 'sr25', userId: 'u4', categoryId: 'edecan', subcategoryId: 'ed1', title: 'Edecanes para evento corporativo',
    description: 'Evento de lanzamiento de producto tecnológico. Necesito 2 edecanes para recepción, registro de invitados y atención general. Duración 6 horas.',
    photos: [], urgency: 'high', status: 'quoted',
    address: { street: 'Calzada del Valle 100', colony: 'Del Valle', city: 'Monterrey', state: 'Nuevo León', zipCode: '66220' },
    createdAt: '2024-07-13T14:00:00Z', updatedAt: '2024-07-14T10:00:00Z',
    timeline: [
      { id: 't56', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-13T14:00:00Z', actor: 'Roberto Sánchez Díaz' },
      { id: 't57', type: 'quoted', description: 'Cotización recibida de Andrea Guzmán', timestamp: '2024-07-14T10:00:00Z', actor: 'Andrea Guzmán Paredes' },
    ],
  },
  {
    id: 'sr26', userId: 'u9', categoryId: 'edecan', subcategoryId: 'ed3', title: 'Edecán para expo de bodas',
    description: 'Busco edecán para atender stand en expo de bodas el próximo fin de semana. Sábado y domingo, 8 horas cada día.',
    photos: [], urgency: 'medium', status: 'completed',
    address: { street: 'Av. Universidad 700', colony: 'Narvarte', city: 'Ciudad de México', state: 'CDMX', zipCode: '03020' },
    createdAt: '2024-07-01T10:00:00Z', updatedAt: '2024-07-07T18:00:00Z',
    assignedWorkerId: 'w21', acceptedQuoteId: 'q26', completedAt: '2024-07-07T18:00:00Z',
    timeline: [
      { id: 't58', type: 'created', description: 'Solicitud creada', timestamp: '2024-07-01T10:00:00Z', actor: 'Sofía Jiménez Reyes' },
      { id: 't59', type: 'quoted', description: 'Cotización recibida', timestamp: '2024-07-02T09:00:00Z', actor: 'Karla Ibáñez Montes' },
      { id: 't60', type: 'accepted', description: 'Cotización aceptada', timestamp: '2024-07-03T08:00:00Z', actor: 'Sofía Jiménez Reyes' },
      { id: 't61', type: 'in_progress', description: 'Trabajo iniciado', timestamp: '2024-07-06T09:00:00Z', actor: 'Karla Ibáñez Montes' },
      { id: 't62', type: 'completed', description: 'Expo completada exitosamente', timestamp: '2024-07-07T18:00:00Z', actor: 'Karla Ibáñez Montes' },
    ],
  },
];
