import { User, WorkerProfile } from '../types';

export const mockUsers: User[] = [
  { id: 'u1', name: 'María García López', email: 'maria@email.com', phone: '+52 55 1234 5678', role: 'user', createdAt: '2024-01-15', avatar: undefined, address: { street: 'Av. Reforma 222', colony: 'Juárez', city: 'Ciudad de México', state: 'CDMX', zipCode: '06600' } },
  { id: 'u2', name: 'Carlos Hernández Ruiz', email: 'carlos@email.com', phone: '+52 55 2345 6789', role: 'user', createdAt: '2024-02-20', avatar: undefined, address: { street: 'Calle Monterrey 45', colony: 'Roma Sur', city: 'Ciudad de México', state: 'CDMX', zipCode: '06700' } },
  { id: 'u3', name: 'Ana Martínez Flores', email: 'ana@email.com', phone: '+52 33 1234 5678', role: 'user', createdAt: '2024-03-10', avatar: undefined, address: { street: 'Av. Vallarta 1200', colony: 'Americana', city: 'Guadalajara', state: 'Jalisco', zipCode: '44160' } },
  { id: 'u4', name: 'Roberto Sánchez Díaz', email: 'roberto@email.com', phone: '+52 81 1234 5678', role: 'user', createdAt: '2024-03-15', avatar: undefined, address: { street: 'Calzada del Valle 100', colony: 'Del Valle', city: 'Monterrey', state: 'Nuevo León', zipCode: '66220' } },
  { id: 'u5', name: 'Laura Rodríguez Morales', email: 'laura@email.com', phone: '+52 55 3456 7890', role: 'user', createdAt: '2024-04-01', avatar: undefined, address: { street: 'Av. Insurgentes Sur 500', colony: 'Del Valle', city: 'Ciudad de México', state: 'CDMX', zipCode: '03100' } },
  { id: 'u6', name: 'Pedro López Castro', email: 'pedro@email.com', phone: '+52 55 4567 8901', role: 'user', createdAt: '2024-04-10', avatar: undefined, address: { street: 'Calle Durango 200', colony: 'Roma Norte', city: 'Ciudad de México', state: 'CDMX', zipCode: '06700' } },
  { id: 'u7', name: 'Fernanda Torres Vega', email: 'fernanda@email.com', phone: '+52 222 1234 567', role: 'user', createdAt: '2024-05-01', avatar: undefined, address: { street: 'Blvd. Atlixcáyotl 1001', colony: 'Reserva Territorial', city: 'Puebla', state: 'Puebla', zipCode: '72810' } },
  { id: 'u8', name: 'Diego Ramírez Ortega', email: 'diego@email.com', phone: '+52 55 5678 9012', role: 'user', createdAt: '2024-05-15', avatar: undefined, address: { street: 'Av. Revolución 300', colony: 'Tacubaya', city: 'Ciudad de México', state: 'CDMX', zipCode: '11870' } },
  { id: 'u9', name: 'Sofía Jiménez Reyes', email: 'sofia@email.com', phone: '+52 55 6789 0123', role: 'user', createdAt: '2024-06-01', avatar: undefined, address: { street: 'Av. Universidad 700', colony: 'Narvarte', city: 'Ciudad de México', state: 'CDMX', zipCode: '03020' } },
  { id: 'u10', name: 'Miguel Ángel Vargas', email: 'miguel@email.com', phone: '+52 55 7890 1234', role: 'user', createdAt: '2024-06-15', avatar: undefined, address: { street: 'Calle Liverpool 50', colony: 'Juárez', city: 'Ciudad de México', state: 'CDMX', zipCode: '06600' } },
];

const defaultSchedule = {
  monday: { available: true, startTime: '08:00', endTime: '18:00' },
  tuesday: { available: true, startTime: '08:00', endTime: '18:00' },
  wednesday: { available: true, startTime: '08:00', endTime: '18:00' },
  thursday: { available: true, startTime: '08:00', endTime: '18:00' },
  friday: { available: true, startTime: '08:00', endTime: '18:00' },
  saturday: { available: true, startTime: '09:00', endTime: '14:00' },
  sunday: { available: false, startTime: '00:00', endTime: '00:00' },
};

export const mockWorkers: WorkerProfile[] = [
  {
    id: 'w1', name: 'Juan Pérez Mendoza', email: 'juan.perez@email.com', phone: '+52 55 1111 2222', role: 'worker', createdAt: '2023-06-01', avatar: undefined,
    bio: 'Plomero certificado con más de 10 años de experiencia. Especialista en instalaciones y reparaciones residenciales.',
    categories: ['plomeria'], rating: 4.8, reviewCount: 127, completedJobs: 234, yearsExperience: 10, verified: true, verificationStatus: 'approved',
    hourlyRate: 350, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/DBEAFE/2563EB?text=Trabajo+1', 'https://placehold.co/400x300/DBEAFE/2563EB?text=Trabajo+2', 'https://placehold.co/400x300/DBEAFE/2563EB?text=Trabajo+3'],
    certifications: [{ id: 'c1', name: 'Plomería Residencial', issuer: 'CONOCER', date: '2020-03-15', verified: true }],
    earnings: { total: 485000, thisMonth: 42000, lastMonth: 38000, pending: 5600, available: 36400 },
    address: { street: 'Calle Aztecas 45', colony: 'Coyoacán', city: 'Ciudad de México', state: 'CDMX', zipCode: '04000' },
  },
  {
    id: 'w2', name: 'Ricardo Gómez Salinas', email: 'ricardo@email.com', phone: '+52 55 2222 3333', role: 'worker', createdAt: '2023-07-15', avatar: undefined,
    bio: 'Electricista profesional. Instalaciones, reparaciones y mantenimiento eléctrico para hogares y negocios.',
    categories: ['electricidad'], rating: 4.9, reviewCount: 98, completedJobs: 189, yearsExperience: 12, verified: true, verificationStatus: 'approved',
    hourlyRate: 400, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/FEF3C7/F59E0B?text=Trabajo+1', 'https://placehold.co/400x300/FEF3C7/F59E0B?text=Trabajo+2'],
    certifications: [{ id: 'c2', name: 'Instalaciones Eléctricas', issuer: 'SEP', date: '2019-08-20', verified: true }],
    earnings: { total: 520000, thisMonth: 45000, lastMonth: 41000, pending: 8200, available: 36800 },
    address: { street: 'Av. Cuauhtémoc 300', colony: 'Narvarte', city: 'Ciudad de México', state: 'CDMX', zipCode: '03020' },
  },
  {
    id: 'w3', name: 'Fernando Castillo Luna', email: 'fernando@email.com', phone: '+52 55 3333 4444', role: 'worker', createdAt: '2023-08-01', avatar: undefined,
    bio: 'Pintor profesional con experiencia en acabados de alta calidad. Interior y exterior.',
    categories: ['pintura'], rating: 4.7, reviewCount: 76, completedJobs: 145, yearsExperience: 8, verified: true, verificationStatus: 'approved',
    hourlyRate: 300, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/D1FAE5/10B981?text=Pintura+1', 'https://placehold.co/400x300/D1FAE5/10B981?text=Pintura+2'],
    certifications: [{ id: 'c3', name: 'Pintura Decorativa', issuer: 'Comex Academy', date: '2021-05-10', verified: true }],
    earnings: { total: 310000, thisMonth: 28000, lastMonth: 32000, pending: 4500, available: 23500 },
    address: { street: 'Calle Mixcoac 120', colony: 'Mixcoac', city: 'Ciudad de México', state: 'CDMX', zipCode: '03910' },
  },
  {
    id: 'w4', name: 'Isabel Navarro Cruz', email: 'isabel@email.com', phone: '+52 55 4444 5555', role: 'worker', createdAt: '2023-09-01', avatar: undefined,
    bio: 'Servicio de limpieza profesional. Limpieza profunda, regular y post-construcción.',
    categories: ['limpieza'], rating: 4.9, reviewCount: 203, completedJobs: 312, yearsExperience: 6, verified: true, verificationStatus: 'approved',
    hourlyRate: 250, availability: defaultSchedule,
    portfolio: [],
    certifications: [{ id: 'c4', name: 'Limpieza Profesional', issuer: 'ISSA', date: '2022-01-15', verified: true }],
    earnings: { total: 420000, thisMonth: 35000, lastMonth: 33000, pending: 3200, available: 31800 },
    address: { street: 'Av. Taxqueña 500', colony: 'Taxqueña', city: 'Ciudad de México', state: 'CDMX', zipCode: '04250' },
  },
  {
    id: 'w5', name: 'Alejandro Moreno Ríos', email: 'alejandro@email.com', phone: '+52 55 5555 6666', role: 'worker', createdAt: '2023-10-01', avatar: undefined,
    bio: 'Cerrajero de confianza. Apertura de puertas, cambio de chapas, instalación de cerraduras de seguridad.',
    categories: ['cerrajeria'], rating: 4.6, reviewCount: 54, completedJobs: 98, yearsExperience: 15, verified: true, verificationStatus: 'approved',
    hourlyRate: 400, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/FEE2E2/EF4444?text=Cerrajeria+1'],
    certifications: [],
    earnings: { total: 280000, thisMonth: 22000, lastMonth: 25000, pending: 2800, available: 19200 },
    address: { street: 'Calle Bolívar 80', colony: 'Centro', city: 'Ciudad de México', state: 'CDMX', zipCode: '06080' },
  },
  {
    id: 'w6', name: 'Martín Aguilar Peña', email: 'martin@email.com', phone: '+52 55 6666 7777', role: 'worker', createdAt: '2023-10-15', avatar: undefined,
    bio: 'Servicio de mudanzas y fletes. Empaque, transporte y desempaque. Equipo profesional.',
    categories: ['mudanzas'], rating: 4.5, reviewCount: 41, completedJobs: 67, yearsExperience: 5, verified: true, verificationStatus: 'approved',
    hourlyRate: 350, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/E0E7FF/6366F1?text=Mudanza+1'],
    certifications: [],
    earnings: { total: 195000, thisMonth: 18000, lastMonth: 20000, pending: 3500, available: 14500 },
    address: { street: 'Calz. de Tlalpan 1500', colony: 'Portales', city: 'Ciudad de México', state: 'CDMX', zipCode: '03300' },
  },
  {
    id: 'w7', name: 'Raúl Delgado Fuentes', email: 'raul@email.com', phone: '+52 55 7777 8888', role: 'worker', createdAt: '2023-11-01', avatar: undefined,
    bio: 'Jardinero profesional. Diseño, mantenimiento y poda de jardines. Sistemas de riego.',
    categories: ['jardineria'], rating: 4.7, reviewCount: 63, completedJobs: 110, yearsExperience: 9, verified: true, verificationStatus: 'approved',
    hourlyRate: 280, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/D1FAE5/059669?text=Jardin+1', 'https://placehold.co/400x300/D1FAE5/059669?text=Jardin+2'],
    certifications: [{ id: 'c7', name: 'Paisajismo', issuer: 'UNAM', date: '2020-11-01', verified: true }],
    earnings: { total: 245000, thisMonth: 20000, lastMonth: 22000, pending: 2100, available: 17900 },
    address: { street: 'Calle Xochimilco 40', colony: 'Xochimilco', city: 'Ciudad de México', state: 'CDMX', zipCode: '16000' },
  },
  {
    id: 'w8', name: 'Héctor Ruiz Vargas', email: 'hector@email.com', phone: '+52 55 8888 9999', role: 'worker', createdAt: '2023-11-15', avatar: undefined,
    bio: 'Técnico en reparaciones generales del hogar. Carpintería, herrería y mantenimiento.',
    categories: ['general', 'plomeria'], rating: 4.4, reviewCount: 38, completedJobs: 72, yearsExperience: 7, verified: true, verificationStatus: 'approved',
    hourlyRate: 320, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/F1F5F9/64748B?text=Reparacion+1'],
    certifications: [],
    earnings: { total: 178000, thisMonth: 15000, lastMonth: 17000, pending: 1800, available: 13200 },
    address: { street: 'Av. Tláhuac 250', colony: 'Tláhuac', city: 'Ciudad de México', state: 'CDMX', zipCode: '13000' },
  },
  {
    id: 'w9', name: 'Gabriela Mendoza Arias', email: 'gabriela@email.com', phone: '+52 33 2222 3333', role: 'worker', createdAt: '2024-01-01', avatar: undefined,
    bio: 'Pintora y decoradora de interiores. Técnicas decorativas, estuco veneciano, papel tapiz.',
    categories: ['pintura'], rating: 4.8, reviewCount: 45, completedJobs: 88, yearsExperience: 6, verified: true, verificationStatus: 'approved',
    hourlyRate: 350, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/D1FAE5/10B981?text=Decoracion+1', 'https://placehold.co/400x300/D1FAE5/10B981?text=Decoracion+2'],
    certifications: [{ id: 'c9', name: 'Diseño de Interiores', issuer: 'ITESM', date: '2021-06-01', verified: true }],
    earnings: { total: 210000, thisMonth: 25000, lastMonth: 23000, pending: 4200, available: 20800 },
    address: { street: 'Av. Chapultepec 500', colony: 'Americana', city: 'Guadalajara', state: 'Jalisco', zipCode: '44160' },
  },
  {
    id: 'w10', name: 'Óscar Vázquez Rojas', email: 'oscar@email.com', phone: '+52 81 3333 4444', role: 'worker', createdAt: '2024-01-15', avatar: undefined,
    bio: 'Electricista y técnico en aires acondicionados. Instalación y mantenimiento.',
    categories: ['electricidad'], rating: 4.6, reviewCount: 32, completedJobs: 55, yearsExperience: 4, verified: false, verificationStatus: 'pending',
    hourlyRate: 380, availability: defaultSchedule,
    portfolio: [],
    certifications: [{ id: 'c10', name: 'Electricidad Industrial', issuer: 'CONALEP', date: '2022-03-01', verified: false }],
    earnings: { total: 95000, thisMonth: 12000, lastMonth: 11000, pending: 2000, available: 10000 },
    address: { street: 'Av. Constitución 800', colony: 'Centro', city: 'Monterrey', state: 'Nuevo León', zipCode: '64000' },
  },
  {
    id: 'w11', name: 'Patricia Solís Campos', email: 'patricia@email.com', phone: '+52 55 9999 0000', role: 'worker', createdAt: '2024-02-01', avatar: undefined,
    bio: 'Limpieza y organización profesional del hogar. Método KonMari certificada.',
    categories: ['limpieza'], rating: 4.9, reviewCount: 87, completedJobs: 156, yearsExperience: 4, verified: true, verificationStatus: 'approved',
    hourlyRate: 280, availability: defaultSchedule,
    portfolio: [],
    certifications: [{ id: 'c11', name: 'KonMari Consultant', issuer: 'KonMari Media', date: '2023-01-01', verified: true }],
    earnings: { total: 185000, thisMonth: 30000, lastMonth: 28000, pending: 2500, available: 27500 },
    address: { street: 'Calle Ámsterdam 150', colony: 'Condesa', city: 'Ciudad de México', state: 'CDMX', zipCode: '06140' },
  },
  {
    id: 'w12', name: 'Luis Enrique Mora', email: 'luis@email.com', phone: '+52 55 0000 1111', role: 'worker', createdAt: '2024-02-15', avatar: undefined,
    bio: 'Plomero especialista en detección de fugas y reparación de tuberías. Servicio 24/7.',
    categories: ['plomeria'], rating: 4.5, reviewCount: 28, completedJobs: 45, yearsExperience: 11, verified: false, verificationStatus: 'pending',
    hourlyRate: 380, availability: defaultSchedule,
    portfolio: [],
    certifications: [],
    earnings: { total: 72000, thisMonth: 10000, lastMonth: 9000, pending: 1500, available: 8500 },
    address: { street: 'Av. Ermita Iztapalapa 600', colony: 'Iztapalapa', city: 'Ciudad de México', state: 'CDMX', zipCode: '09000' },
  },
  {
    id: 'w13', name: 'Carmen Reyes Gutiérrez', email: 'carmen@email.com', phone: '+52 222 4444 5555', role: 'worker', createdAt: '2024-03-01', avatar: undefined,
    bio: 'Servicio integral de limpieza. Hogares, oficinas y post-construcción. Equipo propio.',
    categories: ['limpieza'], rating: 4.3, reviewCount: 19, completedJobs: 34, yearsExperience: 3, verified: false, verificationStatus: 'rejected',
    hourlyRate: 220, availability: defaultSchedule,
    portfolio: [],
    certifications: [],
    earnings: { total: 45000, thisMonth: 8000, lastMonth: 7500, pending: 1200, available: 6800 },
    address: { street: 'Calle 5 de Mayo 100', colony: 'Centro', city: 'Puebla', state: 'Puebla', zipCode: '72000' },
  },
  {
    id: 'w14', name: 'Andrés Figueroa Nava', email: 'andres@email.com', phone: '+52 55 1010 2020', role: 'worker', createdAt: '2024-03-15', avatar: undefined,
    bio: 'Carpintero y reparador general. Muebles a medida, puertas, closets y reparaciones.',
    categories: ['general'], rating: 4.7, reviewCount: 52, completedJobs: 93, yearsExperience: 14, verified: true, verificationStatus: 'approved',
    hourlyRate: 340, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/F1F5F9/64748B?text=Carpinteria+1', 'https://placehold.co/400x300/F1F5F9/64748B?text=Carpinteria+2'],
    certifications: [{ id: 'c14', name: 'Carpintería Fina', issuer: 'CECATI', date: '2018-09-01', verified: true }],
    earnings: { total: 310000, thisMonth: 26000, lastMonth: 24000, pending: 3800, available: 22200 },
    address: { street: 'Calle Madero 200', colony: 'Centro', city: 'Ciudad de México', state: 'CDMX', zipCode: '06000' },
  },
  {
    id: 'w15', name: 'Rosa Elena Pacheco', email: 'rosa@email.com', phone: '+52 33 5555 6666', role: 'worker', createdAt: '2024-04-01', avatar: undefined,
    bio: 'Jardinera y paisajista. Diseño de jardines, mantenimiento y huertos urbanos.',
    categories: ['jardineria'], rating: 4.8, reviewCount: 35, completedJobs: 62, yearsExperience: 5, verified: true, verificationStatus: 'approved',
    hourlyRate: 300, availability: defaultSchedule,
    portfolio: ['https://placehold.co/400x300/D1FAE5/059669?text=Paisaje+1'],
    certifications: [],
    earnings: { total: 125000, thisMonth: 18000, lastMonth: 16000, pending: 2200, available: 15800 },
    address: { street: 'Av. Patria 1000', colony: 'Jardines Universidad', city: 'Guadalajara', state: 'Jalisco', zipCode: '45110' },
  },
];

export const mockAdmin: User = {
  id: 'admin1', name: 'Administrador La palomita azul', email: 'admin@lapalomitaazul.mx', phone: '+52 55 0000 0000', role: 'admin', createdAt: '2023-01-01', avatar: undefined,
};
